[package]
name = "host"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
figment.workspace = true
rustls.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true